### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#65]
Hey @mradamcox - We can't seem to scroll on the Arches website (even in Chrome). You can scroll on individual resources pages but not on the main page (through the search bar) or when filling out a scout report. There may be other portions but this is what I've noticed for now. Thanks!

**Comment by mradamcox** [comment]
Hi @emjaymur I think I have this fixed now, though it's a very strange issue to pop up all of a sudden! I believe the fix I made works across the site, and should hold us until the upgrade is completed, but please let me know if you find any other strangeness that seems related to height/scrollbars.

**Comment by mradamcox** [comment]
You may have to hard refresh the browser for the new css to take effect.

**Comment by emjaymur** [comment]
I still can't get it to scroll. I tried the hard refresh. :-/

**Comment by rosulliv14** [comment]
I just logged in on the admin account and was able to scroll down in the search bar and scout report sections, tried with another login and that worked for me too - but maybe I'm not looking to scroll in the same places you were? Will try some more to replicate on my computer

**Comment by mradamcox** [comment]
@emjaymur and @rosulliv14 I think I have this fixed now, could you do some testing and let me know? It's more of a temp fix that should be sufficient until the v4 upgrade is completed.
