### ISSUE TITLE
Tileserver Layer error when saving new historic structure point

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#87]
When trying to create a new historic structure, everything is fine until a new geometry is created. There is an error during the save indicating a tileserver layer does not exist. However, the geometry is somehow present in the search page.

**Comment by mradamcox** [comment]
@kkemp85 @emjaymur can you test this out? It should be fixed now.

**Comment by kkemp85** [comment]
@mradamcox I actually tested this out earlier today and I am still getting the same error

**Comment by mradamcox** [comment]
@kkemp85 I think this is now solved.

**Comment by kkemp85** [comment]
I'm still getting the error Saving tile failed - OSError when I try it, maybe it's something I'm doing wrong? I'm adding the coordinates as a point.

**Comment by kkemp85** [comment]
@mradamcox this is fixed now!
